// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';
import 'puente.dart';

abstract class NucleoApiImplPlatform extends BaseApiImpl<NucleoWire> {
  NucleoApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AvisoDto dco_decode_aviso_dto(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  EventoDto dco_decode_box_autoadd_evento_dto(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  EventoDto dco_decode_evento_dto(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FraseDto dco_decode_frase_dto(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<AvisoDto> dco_decode_list_aviso_dto(dynamic raw);

  @protected
  List<FraseDto> dco_decode_list_frase_dto(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ProveedorDto> dco_decode_list_proveedor_dto(dynamic raw);

  @protected
  List<SesionDto> dco_decode_list_sesion_dto(dynamic raw);

  @protected
  List<TopicDto> dco_decode_list_topic_dto(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  EventoDto? dco_decode_opt_box_autoadd_evento_dto(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  ProcesadaDto dco_decode_procesada_dto(dynamic raw);

  @protected
  ProveedorDto dco_decode_proveedor_dto(dynamic raw);

  @protected
  SesionDto dco_decode_sesion_dto(dynamic raw);

  @protected
  TopicDto dco_decode_topic_dto(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AvisoDto sse_decode_aviso_dto(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  EventoDto sse_decode_box_autoadd_evento_dto(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  EventoDto sse_decode_evento_dto(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FraseDto sse_decode_frase_dto(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<AvisoDto> sse_decode_list_aviso_dto(SseDeserializer deserializer);

  @protected
  List<FraseDto> sse_decode_list_frase_dto(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ProveedorDto> sse_decode_list_proveedor_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<SesionDto> sse_decode_list_sesion_dto(SseDeserializer deserializer);

  @protected
  List<TopicDto> sse_decode_list_topic_dto(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  EventoDto? sse_decode_opt_box_autoadd_evento_dto(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  ProcesadaDto sse_decode_procesada_dto(SseDeserializer deserializer);

  @protected
  ProveedorDto sse_decode_proveedor_dto(SseDeserializer deserializer);

  @protected
  SesionDto sse_decode_sesion_dto(SseDeserializer deserializer);

  @protected
  TopicDto sse_decode_topic_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_aviso_dto(AvisoDto self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_evento_dto(
    EventoDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_evento_dto(EventoDto self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_frase_dto(FraseDto self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_aviso_dto(List<AvisoDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_frase_dto(List<FraseDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_proveedor_dto(
    List<ProveedorDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_sesion_dto(
    List<SesionDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_topic_dto(List<TopicDto> self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_evento_dto(
    EventoDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_procesada_dto(ProcesadaDto self, SseSerializer serializer);

  @protected
  void sse_encode_proveedor_dto(ProveedorDto self, SseSerializer serializer);

  @protected
  void sse_encode_sesion_dto(SesionDto self, SseSerializer serializer);

  @protected
  void sse_encode_topic_dto(TopicDto self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class NucleoWire implements BaseWire {
  NucleoWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external NucleoWasmModule get wasmModule;

@JS()
@anonymous
extension type NucleoWasmModule._(JSObject _) implements JSObject {}
