// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'puente.dart';

/// Main entrypoint of the Rust API
class Nucleo extends BaseEntrypoint<NucleoApi, NucleoApiImpl, NucleoWire> {
  @internal
  static final instance = Nucleo._();

  Nucleo._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    NucleoApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required NucleoApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<NucleoApiImpl, NucleoWire> get apiImplConstructor =>
      NucleoApiImpl.new;

  @override
  WireConstructor<NucleoWire> get wireConstructor =>
      NucleoWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -408904154;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'dictar_api',
        ioDirectory: '../core/api/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class NucleoApi extends BaseApi {
  Future<List<FraseDto>> cratePuenteBuscar({required String consulta});

  Future<List<String>> cratePuenteCarpetasSugeridas();

  Future<String> cratePuenteCrearTopic({
    required String nombre,
    String? persona,
    required bool esCliente,
  });

  Future<void> cratePuenteDescartarAviso({required PlatformInt64 id});

  Future<String> cratePuenteDetenerGrabacion({required PlatformInt64 ahoraMs});

  Future<EventoDto> cratePuenteEventoDtoDefault();

  Future<String?> cratePuenteExportarApuntes({required String sessionId});

  Future<String?> cratePuenteGrabando();

  Future<void> cratePuenteGuardarAjustes({
    String? carpetaApuntes,
    String? modelo,
    required bool capturarDiapositivas,
  });

  Future<String> cratePuenteGuardarClave({
    required String proveedor,
    String? clave,
  });

  Future<String> cratePuenteInicializar({String? dirDatos});

  Future<String> cratePuenteIniciarGrabacion({
    required String tipo,
    String? topicId,
    String? titulo,
    required bool capturarSistema,
    required bool capturarDiapositivas,
    required bool soloLocal,
    required PlatformInt64 ahoraMs,
  });

  Future<List<AvisoDto>> cratePuenteListarPendientes();

  Future<List<ProveedorDto>> cratePuenteListarProveedores();

  Future<List<SesionDto>> cratePuenteListarSesiones({required int limite});

  Future<List<TopicDto>> cratePuenteListarTopics();

  Future<AjustesDto> cratePuenteObtenerAjustes();

  Future<String?> cratePuenteObtenerNotas({required String sessionId});

  Future<List<FraseDto>> cratePuenteObtenerTranscripcion({
    required String sessionId,
  });

  Future<String> cratePuenteProbarProveedor({required String id});

  Future<ProcesadaDto> cratePuenteProcesarSesion({
    required String sessionId,
    required PlatformInt64 ahoraMs,
  });

  Future<List<SesionDto>> cratePuenteSesionesInterrumpidas();

  Future<EventoDto?> cratePuenteSiguienteEvento({required int esperaMs});
}

class NucleoApiImpl extends NucleoApiImplPlatform implements NucleoApi {
  NucleoApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<List<FraseDto>> cratePuenteBuscar({required String consulta}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(consulta, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_frase_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCratePuenteBuscarConstMeta,
        argValues: [consulta],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCratePuenteBuscarConstMeta =>
      const TaskConstMeta(debugName: "buscar", argNames: ["consulta"]);

  @override
  Future<List<String>> cratePuenteCarpetasSugeridas() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCratePuenteCarpetasSugeridasConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCratePuenteCarpetasSugeridasConstMeta =>
      const TaskConstMeta(debugName: "carpetas_sugeridas", argNames: []);

  @override
  Future<String> cratePuenteCrearTopic({
    required String nombre,
    String? persona,
    required bool esCliente,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(nombre, serializer);
          sse_encode_opt_String(persona, serializer);
          sse_encode_bool(esCliente, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCratePuenteCrearTopicConstMeta,
        argValues: [nombre, persona, esCliente],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCratePuenteCrearTopicConstMeta => const TaskConstMeta(
    debugName: "crear_topic",
    argNames: ["nombre", "persona", "esCliente"],
  );

  @override
  Future<void> cratePuenteDescartarAviso({required PlatformInt64 id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCratePuenteDescartarAvisoConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCratePuenteDescartarAvisoConstMeta =>
      const TaskConstMeta(debugName: "descartar_aviso", argNames: ["id"]);

  @override
  Future<String> cratePuenteDetenerGrabacion({required PlatformInt64 ahoraMs}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(ahoraMs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCratePuenteDetenerGrabacionConstMeta,
        argValues: [ahoraMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCratePuenteDetenerGrabacionConstMeta =>
      const TaskConstMeta(
        debugName: "detener_grabacion",
        argNames: ["ahoraMs"],
      );

  @override
  Future<EventoDto> cratePuenteEventoDtoDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_evento_dto,
          decodeErrorData: null,
        ),
        constMeta: kCratePuenteEventoDtoDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCratePuenteEventoDtoDefaultConstMeta =>
      const TaskConstMeta(debugName: "evento_dto_default", argNames: []);

  @override
  Future<String?> cratePuenteExportarApuntes({required String sessionId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCratePuenteExportarApuntesConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCratePuenteExportarApuntesConstMeta => const TaskConstMeta(
    debugName: "exportar_apuntes",
    argNames: ["sessionId"],
  );

  @override
  Future<String?> cratePuenteGrabando() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCratePuenteGrabandoConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCratePuenteGrabandoConstMeta =>
      const TaskConstMeta(debugName: "grabando", argNames: []);

  @override
  Future<void> cratePuenteGuardarAjustes({
    String? carpetaApuntes,
    String? modelo,
    required bool capturarDiapositivas,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(carpetaApuntes, serializer);
          sse_encode_opt_String(modelo, serializer);
          sse_encode_bool(capturarDiapositivas, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCratePuenteGuardarAjustesConstMeta,
        argValues: [carpetaApuntes, modelo, capturarDiapositivas],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCratePuenteGuardarAjustesConstMeta => const TaskConstMeta(
    debugName: "guardar_ajustes",
    argNames: ["carpetaApuntes", "modelo", "capturarDiapositivas"],
  );

  @override
  Future<String> cratePuenteGuardarClave({
    required String proveedor,
    String? clave,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(proveedor, serializer);
          sse_encode_opt_String(clave, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCratePuenteGuardarClaveConstMeta,
        argValues: [proveedor, clave],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCratePuenteGuardarClaveConstMeta => const TaskConstMeta(
    debugName: "guardar_clave",
    argNames: ["proveedor", "clave"],
  );

  @override
  Future<String> cratePuenteInicializar({String? dirDatos}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(dirDatos, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCratePuenteInicializarConstMeta,
        argValues: [dirDatos],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCratePuenteInicializarConstMeta =>
      const TaskConstMeta(debugName: "inicializar", argNames: ["dirDatos"]);

  @override
  Future<String> cratePuenteIniciarGrabacion({
    required String tipo,
    String? topicId,
    String? titulo,
    required bool capturarSistema,
    required bool capturarDiapositivas,
    required bool soloLocal,
    required PlatformInt64 ahoraMs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(tipo, serializer);
          sse_encode_opt_String(topicId, serializer);
          sse_encode_opt_String(titulo, serializer);
          sse_encode_bool(capturarSistema, serializer);
          sse_encode_bool(capturarDiapositivas, serializer);
          sse_encode_bool(soloLocal, serializer);
          sse_encode_i_64(ahoraMs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCratePuenteIniciarGrabacionConstMeta,
        argValues: [
          tipo,
          topicId,
          titulo,
          capturarSistema,
          capturarDiapositivas,
          soloLocal,
          ahoraMs,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCratePuenteIniciarGrabacionConstMeta =>
      const TaskConstMeta(
        debugName: "iniciar_grabacion",
        argNames: [
          "tipo",
          "topicId",
          "titulo",
          "capturarSistema",
          "capturarDiapositivas",
          "soloLocal",
          "ahoraMs",
        ],
      );

  @override
  Future<List<AvisoDto>> cratePuenteListarPendientes() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_aviso_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCratePuenteListarPendientesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCratePuenteListarPendientesConstMeta =>
      const TaskConstMeta(debugName: "listar_pendientes", argNames: []);

  @override
  Future<List<ProveedorDto>> cratePuenteListarProveedores() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_proveedor_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCratePuenteListarProveedoresConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCratePuenteListarProveedoresConstMeta =>
      const TaskConstMeta(debugName: "listar_proveedores", argNames: []);

  @override
  Future<List<SesionDto>> cratePuenteListarSesiones({required int limite}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(limite, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_sesion_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCratePuenteListarSesionesConstMeta,
        argValues: [limite],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCratePuenteListarSesionesConstMeta =>
      const TaskConstMeta(debugName: "listar_sesiones", argNames: ["limite"]);

  @override
  Future<List<TopicDto>> cratePuenteListarTopics() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_topic_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCratePuenteListarTopicsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCratePuenteListarTopicsConstMeta =>
      const TaskConstMeta(debugName: "listar_topics", argNames: []);

  @override
  Future<AjustesDto> cratePuenteObtenerAjustes() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_ajustes_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCratePuenteObtenerAjustesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCratePuenteObtenerAjustesConstMeta =>
      const TaskConstMeta(debugName: "obtener_ajustes", argNames: []);

  @override
  Future<String?> cratePuenteObtenerNotas({required String sessionId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCratePuenteObtenerNotasConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCratePuenteObtenerNotasConstMeta =>
      const TaskConstMeta(debugName: "obtener_notas", argNames: ["sessionId"]);

  @override
  Future<List<FraseDto>> cratePuenteObtenerTranscripcion({
    required String sessionId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_frase_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCratePuenteObtenerTranscripcionConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCratePuenteObtenerTranscripcionConstMeta =>
      const TaskConstMeta(
        debugName: "obtener_transcripcion",
        argNames: ["sessionId"],
      );

  @override
  Future<String> cratePuenteProbarProveedor({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCratePuenteProbarProveedorConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCratePuenteProbarProveedorConstMeta =>
      const TaskConstMeta(debugName: "probar_proveedor", argNames: ["id"]);

  @override
  Future<ProcesadaDto> cratePuenteProcesarSesion({
    required String sessionId,
    required PlatformInt64 ahoraMs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          sse_encode_i_64(ahoraMs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_procesada_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCratePuenteProcesarSesionConstMeta,
        argValues: [sessionId, ahoraMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCratePuenteProcesarSesionConstMeta => const TaskConstMeta(
    debugName: "procesar_sesion",
    argNames: ["sessionId", "ahoraMs"],
  );

  @override
  Future<List<SesionDto>> cratePuenteSesionesInterrumpidas() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_sesion_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCratePuenteSesionesInterrumpidasConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCratePuenteSesionesInterrumpidasConstMeta =>
      const TaskConstMeta(debugName: "sesiones_interrumpidas", argNames: []);

  @override
  Future<EventoDto?> cratePuenteSiguienteEvento({required int esperaMs}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(esperaMs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_evento_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCratePuenteSiguienteEventoConstMeta,
        argValues: [esperaMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCratePuenteSiguienteEventoConstMeta => const TaskConstMeta(
    debugName: "siguiente_evento",
    argNames: ["esperaMs"],
  );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AjustesDto dco_decode_ajustes_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return AjustesDto(
      carpetaApuntes: dco_decode_opt_String(arr[0]),
      carpetaEfectiva: dco_decode_opt_String(arr[1]),
      modelo: dco_decode_opt_String(arr[2]),
      capturarDiapositivas: dco_decode_bool(arr[3]),
    );
  }

  @protected
  AvisoDto dco_decode_aviso_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return AvisoDto(
      id: dco_decode_i_64(arr[0]),
      sessionId: dco_decode_String(arr[1]),
      topicId: dco_decode_opt_String(arr[2]),
      kind: dco_decode_String(arr[3]),
      texto: dco_decode_String(arr[4]),
      fecha: dco_decode_opt_String(arr[5]),
      tsMs: dco_decode_i_64(arr[6]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  EventoDto dco_decode_box_autoadd_evento_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_evento_dto(raw);
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  EventoDto dco_decode_evento_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 15)
      throw Exception('unexpected arr length: expect 15 but see ${arr.length}');
    return EventoDto(
      tipo: dco_decode_String(arr[0]),
      nivelMic: dco_decode_f_32(arr[1]),
      nivelSistema: dco_decode_f_32(arr[2]),
      transcurridoMs: dco_decode_i_64(arr[3]),
      track: dco_decode_opt_String(arr[4]),
      texto: dco_decode_opt_String(arr[5]),
      inicioMs: dco_decode_i_64(arr[6]),
      finMs: dco_decode_i_64(arr[7]),
      definitiva: dco_decode_bool(arr[8]),
      fase: dco_decode_opt_String(arr[9]),
      fraccion: dco_decode_f_32(arr[10]),
      detalle: dco_decode_opt_String(arr[11]),
      costeUsd: dco_decode_f_64(arr[12]),
      avisos: dco_decode_i_64(arr[13]),
      mensaje: dco_decode_opt_String(arr[14]),
    );
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  FraseDto dco_decode_frase_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return FraseDto(
      track: dco_decode_String(arr[0]),
      speaker: dco_decode_opt_String(arr[1]),
      inicioMs: dco_decode_i_64(arr[2]),
      finMs: dco_decode_i_64(arr[3]),
      texto: dco_decode_String(arr[4]),
      definitiva: dco_decode_bool(arr[5]),
    );
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<AvisoDto> dco_decode_list_aviso_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_aviso_dto).toList();
  }

  @protected
  List<FraseDto> dco_decode_list_frase_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_frase_dto).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<ProveedorDto> dco_decode_list_proveedor_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_proveedor_dto).toList();
  }

  @protected
  List<SesionDto> dco_decode_list_sesion_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_sesion_dto).toList();
  }

  @protected
  List<TopicDto> dco_decode_list_topic_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_topic_dto).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  EventoDto? dco_decode_opt_box_autoadd_evento_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_evento_dto(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  ProcesadaDto dco_decode_procesada_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return ProcesadaDto(
      sessionId: dco_decode_String(arr[0]),
      frases: dco_decode_i_64(arr[1]),
      avisos: dco_decode_i_64(arr[2]),
      costeUsd: dco_decode_f_64(arr[3]),
      proveedor: dco_decode_String(arr[4]),
    );
  }

  @protected
  ProveedorDto dco_decode_proveedor_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ProveedorDto(
      id: dco_decode_String(arr[0]),
      modelo: dco_decode_String(arr[1]),
      origenClave: dco_decode_opt_String(arr[2]),
      esLocal: dco_decode_bool(arr[3]),
    );
  }

  @protected
  SesionDto dco_decode_sesion_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return SesionDto(
      id: dco_decode_String(arr[0]),
      topicId: dco_decode_opt_String(arr[1]),
      kind: dco_decode_String(arr[2]),
      status: dco_decode_String(arr[3]),
      title: dco_decode_opt_String(arr[4]),
      startedAt: dco_decode_i_64(arr[5]),
      endedAt: dco_decode_opt_box_autoadd_i_64(arr[6]),
      appCaptured: dco_decode_opt_String(arr[7]),
      numDiapositivas: dco_decode_i_64(arr[8]),
      costeUsd: dco_decode_f_64(arr[9]),
    );
  }

  @protected
  TopicDto dco_decode_topic_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return TopicDto(
      id: dco_decode_String(arr[0]),
      kind: dco_decode_String(arr[1]),
      name: dco_decode_String(arr[2]),
      person: dco_decode_opt_String(arr[3]),
      term: dco_decode_opt_String(arr[4]),
      consentAck: dco_decode_bool(arr[5]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AjustesDto sse_decode_ajustes_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_carpetaApuntes = sse_decode_opt_String(deserializer);
    var var_carpetaEfectiva = sse_decode_opt_String(deserializer);
    var var_modelo = sse_decode_opt_String(deserializer);
    var var_capturarDiapositivas = sse_decode_bool(deserializer);
    return AjustesDto(
      carpetaApuntes: var_carpetaApuntes,
      carpetaEfectiva: var_carpetaEfectiva,
      modelo: var_modelo,
      capturarDiapositivas: var_capturarDiapositivas,
    );
  }

  @protected
  AvisoDto sse_decode_aviso_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_64(deserializer);
    var var_sessionId = sse_decode_String(deserializer);
    var var_topicId = sse_decode_opt_String(deserializer);
    var var_kind = sse_decode_String(deserializer);
    var var_texto = sse_decode_String(deserializer);
    var var_fecha = sse_decode_opt_String(deserializer);
    var var_tsMs = sse_decode_i_64(deserializer);
    return AvisoDto(
      id: var_id,
      sessionId: var_sessionId,
      topicId: var_topicId,
      kind: var_kind,
      texto: var_texto,
      fecha: var_fecha,
      tsMs: var_tsMs,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  EventoDto sse_decode_box_autoadd_evento_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_evento_dto(deserializer));
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  EventoDto sse_decode_evento_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_tipo = sse_decode_String(deserializer);
    var var_nivelMic = sse_decode_f_32(deserializer);
    var var_nivelSistema = sse_decode_f_32(deserializer);
    var var_transcurridoMs = sse_decode_i_64(deserializer);
    var var_track = sse_decode_opt_String(deserializer);
    var var_texto = sse_decode_opt_String(deserializer);
    var var_inicioMs = sse_decode_i_64(deserializer);
    var var_finMs = sse_decode_i_64(deserializer);
    var var_definitiva = sse_decode_bool(deserializer);
    var var_fase = sse_decode_opt_String(deserializer);
    var var_fraccion = sse_decode_f_32(deserializer);
    var var_detalle = sse_decode_opt_String(deserializer);
    var var_costeUsd = sse_decode_f_64(deserializer);
    var var_avisos = sse_decode_i_64(deserializer);
    var var_mensaje = sse_decode_opt_String(deserializer);
    return EventoDto(
      tipo: var_tipo,
      nivelMic: var_nivelMic,
      nivelSistema: var_nivelSistema,
      transcurridoMs: var_transcurridoMs,
      track: var_track,
      texto: var_texto,
      inicioMs: var_inicioMs,
      finMs: var_finMs,
      definitiva: var_definitiva,
      fase: var_fase,
      fraccion: var_fraccion,
      detalle: var_detalle,
      costeUsd: var_costeUsd,
      avisos: var_avisos,
      mensaje: var_mensaje,
    );
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  FraseDto sse_decode_frase_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_track = sse_decode_String(deserializer);
    var var_speaker = sse_decode_opt_String(deserializer);
    var var_inicioMs = sse_decode_i_64(deserializer);
    var var_finMs = sse_decode_i_64(deserializer);
    var var_texto = sse_decode_String(deserializer);
    var var_definitiva = sse_decode_bool(deserializer);
    return FraseDto(
      track: var_track,
      speaker: var_speaker,
      inicioMs: var_inicioMs,
      finMs: var_finMs,
      texto: var_texto,
      definitiva: var_definitiva,
    );
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<AvisoDto> sse_decode_list_aviso_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <AvisoDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_aviso_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<FraseDto> sse_decode_list_frase_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FraseDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_frase_dto(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<ProveedorDto> sse_decode_list_proveedor_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ProveedorDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_proveedor_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<SesionDto> sse_decode_list_sesion_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SesionDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_sesion_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<TopicDto> sse_decode_list_topic_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TopicDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_topic_dto(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  EventoDto? sse_decode_opt_box_autoadd_evento_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_evento_dto(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ProcesadaDto sse_decode_procesada_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sessionId = sse_decode_String(deserializer);
    var var_frases = sse_decode_i_64(deserializer);
    var var_avisos = sse_decode_i_64(deserializer);
    var var_costeUsd = sse_decode_f_64(deserializer);
    var var_proveedor = sse_decode_String(deserializer);
    return ProcesadaDto(
      sessionId: var_sessionId,
      frases: var_frases,
      avisos: var_avisos,
      costeUsd: var_costeUsd,
      proveedor: var_proveedor,
    );
  }

  @protected
  ProveedorDto sse_decode_proveedor_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_modelo = sse_decode_String(deserializer);
    var var_origenClave = sse_decode_opt_String(deserializer);
    var var_esLocal = sse_decode_bool(deserializer);
    return ProveedorDto(
      id: var_id,
      modelo: var_modelo,
      origenClave: var_origenClave,
      esLocal: var_esLocal,
    );
  }

  @protected
  SesionDto sse_decode_sesion_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_topicId = sse_decode_opt_String(deserializer);
    var var_kind = sse_decode_String(deserializer);
    var var_status = sse_decode_String(deserializer);
    var var_title = sse_decode_opt_String(deserializer);
    var var_startedAt = sse_decode_i_64(deserializer);
    var var_endedAt = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_appCaptured = sse_decode_opt_String(deserializer);
    var var_numDiapositivas = sse_decode_i_64(deserializer);
    var var_costeUsd = sse_decode_f_64(deserializer);
    return SesionDto(
      id: var_id,
      topicId: var_topicId,
      kind: var_kind,
      status: var_status,
      title: var_title,
      startedAt: var_startedAt,
      endedAt: var_endedAt,
      appCaptured: var_appCaptured,
      numDiapositivas: var_numDiapositivas,
      costeUsd: var_costeUsd,
    );
  }

  @protected
  TopicDto sse_decode_topic_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_kind = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_person = sse_decode_opt_String(deserializer);
    var var_term = sse_decode_opt_String(deserializer);
    var var_consentAck = sse_decode_bool(deserializer);
    return TopicDto(
      id: var_id,
      kind: var_kind,
      name: var_name,
      person: var_person,
      term: var_term,
      consentAck: var_consentAck,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_ajustes_dto(AjustesDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.carpetaApuntes, serializer);
    sse_encode_opt_String(self.carpetaEfectiva, serializer);
    sse_encode_opt_String(self.modelo, serializer);
    sse_encode_bool(self.capturarDiapositivas, serializer);
  }

  @protected
  void sse_encode_aviso_dto(AvisoDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.id, serializer);
    sse_encode_String(self.sessionId, serializer);
    sse_encode_opt_String(self.topicId, serializer);
    sse_encode_String(self.kind, serializer);
    sse_encode_String(self.texto, serializer);
    sse_encode_opt_String(self.fecha, serializer);
    sse_encode_i_64(self.tsMs, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_evento_dto(
    EventoDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_evento_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_evento_dto(EventoDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.tipo, serializer);
    sse_encode_f_32(self.nivelMic, serializer);
    sse_encode_f_32(self.nivelSistema, serializer);
    sse_encode_i_64(self.transcurridoMs, serializer);
    sse_encode_opt_String(self.track, serializer);
    sse_encode_opt_String(self.texto, serializer);
    sse_encode_i_64(self.inicioMs, serializer);
    sse_encode_i_64(self.finMs, serializer);
    sse_encode_bool(self.definitiva, serializer);
    sse_encode_opt_String(self.fase, serializer);
    sse_encode_f_32(self.fraccion, serializer);
    sse_encode_opt_String(self.detalle, serializer);
    sse_encode_f_64(self.costeUsd, serializer);
    sse_encode_i_64(self.avisos, serializer);
    sse_encode_opt_String(self.mensaje, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_frase_dto(FraseDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.track, serializer);
    sse_encode_opt_String(self.speaker, serializer);
    sse_encode_i_64(self.inicioMs, serializer);
    sse_encode_i_64(self.finMs, serializer);
    sse_encode_String(self.texto, serializer);
    sse_encode_bool(self.definitiva, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_aviso_dto(
    List<AvisoDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_aviso_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_frase_dto(
    List<FraseDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_frase_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_proveedor_dto(
    List<ProveedorDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_proveedor_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_sesion_dto(
    List<SesionDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_sesion_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_topic_dto(
    List<TopicDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_topic_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_evento_dto(
    EventoDto? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_evento_dto(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_procesada_dto(ProcesadaDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.sessionId, serializer);
    sse_encode_i_64(self.frases, serializer);
    sse_encode_i_64(self.avisos, serializer);
    sse_encode_f_64(self.costeUsd, serializer);
    sse_encode_String(self.proveedor, serializer);
  }

  @protected
  void sse_encode_proveedor_dto(ProveedorDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.modelo, serializer);
    sse_encode_opt_String(self.origenClave, serializer);
    sse_encode_bool(self.esLocal, serializer);
  }

  @protected
  void sse_encode_sesion_dto(SesionDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_opt_String(self.topicId, serializer);
    sse_encode_String(self.kind, serializer);
    sse_encode_String(self.status, serializer);
    sse_encode_opt_String(self.title, serializer);
    sse_encode_i_64(self.startedAt, serializer);
    sse_encode_opt_box_autoadd_i_64(self.endedAt, serializer);
    sse_encode_opt_String(self.appCaptured, serializer);
    sse_encode_i_64(self.numDiapositivas, serializer);
    sse_encode_f_64(self.costeUsd, serializer);
  }

  @protected
  void sse_encode_topic_dto(TopicDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.kind, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_opt_String(self.person, serializer);
    sse_encode_opt_String(self.term, serializer);
    sse_encode_bool(self.consentAck, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
