// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `nucleo`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`

/// Abre el almacén del usuario. Debe llamarse una vez al arrancar.
///
/// Pasar `None` usa la carpeta estándar del sistema.
Future<String> inicializar({String? dirDatos}) =>
    Nucleo.instance.api.cratePuenteInicializar(dirDatos: dirDatos);

Future<List<TopicDto>> listarTopics() =>
    Nucleo.instance.api.cratePuenteListarTopics();

Future<String> crearTopic({
  required String nombre,
  String? persona,
  required bool esCliente,
}) => Nucleo.instance.api.cratePuenteCrearTopic(
  nombre: nombre,
  persona: persona,
  esCliente: esCliente,
);

Future<List<SesionDto>> listarSesiones({required int limite}) =>
    Nucleo.instance.api.cratePuenteListarSesiones(limite: limite);

Future<List<FraseDto>> obtenerTranscripcion({required String sessionId}) =>
    Nucleo.instance.api.cratePuenteObtenerTranscripcion(sessionId: sessionId);

/// Notas ya renderizadas en Markdown.
Future<String?> obtenerNotas({required String sessionId}) =>
    Nucleo.instance.api.cratePuenteObtenerNotas(sessionId: sessionId);

Future<List<AvisoDto>> listarPendientes() =>
    Nucleo.instance.api.cratePuenteListarPendientes();

Future<void> descartarAviso({required PlatformInt64 id}) =>
    Nucleo.instance.api.cratePuenteDescartarAviso(id: id);

Future<List<FraseDto>> buscar({required String consulta}) =>
    Nucleo.instance.api.cratePuenteBuscar(consulta: consulta);

/// Sesiones que quedaron a medias por un cierre inesperado.
Future<List<SesionDto>> sesionesInterrumpidas() =>
    Nucleo.instance.api.cratePuenteSesionesInterrumpidas();

/// Estado de los proveedores de IA, para la pantalla de ajustes.
Future<List<ProveedorDto>> listarProveedores() =>
    Nucleo.instance.api.cratePuenteListarProveedores();

/// Guarda la clave de API de un proveedor, o la borra con `None`.
///
/// Escribe en `~/.config/dictar_ia/.env` con permisos 0600. Surte efecto en la
/// siguiente petición, sin reiniciar: el router se construye en cada uso.
Future<String> guardarClave({required String proveedor, String? clave}) =>
    Nucleo.instance.api.cratePuenteGuardarClave(
      proveedor: proveedor,
      clave: clave,
    );

/// Comprueba que un proveedor responde de verdad.
///
/// Hace una petición mínima real en lugar de validar el formato de la clave:
/// una clave con la forma correcta pero revocada, o un identificador de modelo
/// que ya no existe, solo se detectan preguntando. Descubrirlo aquí y no a
/// mitad de una clase es toda la diferencia.
Future<String> probarProveedor({required String id}) =>
    Nucleo.instance.api.cratePuenteProbarProveedor(id: id);

Future<AjustesDto> obtenerAjustes() =>
    Nucleo.instance.api.cratePuenteObtenerAjustes();

Future<void> guardarAjustes({
  String? carpetaApuntes,
  String? modelo,
  required bool capturarDiapositivas,
}) => Nucleo.instance.api.cratePuenteGuardarAjustes(
  carpetaApuntes: carpetaApuntes,
  modelo: modelo,
  capturarDiapositivas: capturarDiapositivas,
);

/// Carpetas de sincronización detectadas en el equipo, para sugerirlas.
Future<List<String>> carpetasSugeridas() =>
    Nucleo.instance.api.cratePuenteCarpetasSugeridas();

/// Exporta los apuntes de una sesión a la carpeta configurada.
Future<String?> exportarApuntes({required String sessionId}) =>
    Nucleo.instance.api.cratePuenteExportarApuntes(sessionId: sessionId);

Future<String> iniciarGrabacion({
  required String tipo,
  String? topicId,
  String? titulo,
  required bool capturarSistema,
  required bool capturarDiapositivas,
  required bool soloLocal,
  required PlatformInt64 ahoraMs,
}) => Nucleo.instance.api.cratePuenteIniciarGrabacion(
  tipo: tipo,
  topicId: topicId,
  titulo: titulo,
  capturarSistema: capturarSistema,
  capturarDiapositivas: capturarDiapositivas,
  soloLocal: soloLocal,
  ahoraMs: ahoraMs,
);

Future<String> detenerGrabacion({required PlatformInt64 ahoraMs}) =>
    Nucleo.instance.api.cratePuenteDetenerGrabacion(ahoraMs: ahoraMs);

/// Guarda una captura de la pantalla en la sesión en curso.
///
/// Devuelve la ruta del archivo. Falla si no se está grabando.
Future<String> capturarDiapositiva() =>
    Nucleo.instance.api.cratePuenteCapturarDiapositiva();

Future<String?> grabando() => Nucleo.instance.api.cratePuenteGrabando();

/// Vacía la cola de eventos de la grabación o del procesado en curso.
///
/// **No bloquea.** La versión anterior esperaba hasta 200 ms dentro del canal
/// y con el mutex tomado, y eso provocó un fallo serio: la interfaz consultaba
/// cada 120 ms, así que las llamadas llegaban más deprisa de lo que se
/// resolvían, se acumulaban y acababan agotando el grupo de hilos del puente.
/// Con el grupo lleno, cualquier otra llamada —detener la grabación, por
/// ejemplo— se quedaba esperando un hilo que nunca llegaba, y el botón parecía
/// no funcionar.
///
/// Devolviendo de golpe todo lo que hay pendiente, cada llamada dura
/// microsegundos y no hay forma de que se solapen.
Future<List<EventoDto>> eventosPendientes() =>
    Nucleo.instance.api.cratePuenteEventosPendientes();

/// Transcribe y genera las notas de una sesión ya grabada.
///
/// Es la llamada larga —minutos— así que en Dart va en un aislado propio para
/// no bloquear la interfaz.
Future<ProcesadaDto> procesarSesion({
  required String sessionId,
  required PlatformInt64 ahoraMs,
}) => Nucleo.instance.api.cratePuenteProcesarSesion(
  sessionId: sessionId,
  ahoraMs: ahoraMs,
);

class AjustesDto {
  /// Lo que el usuario configuró, o `None` si nunca tocó nada.
  final String? carpetaApuntes;

  /// La que se usa de verdad: la configurada, o la de por defecto dentro de
  /// Documentos. La interfaz enseña esta.
  final String? carpetaEfectiva;
  final String? modelo;
  final bool capturarDiapositivas;

  const AjustesDto({
    this.carpetaApuntes,
    this.carpetaEfectiva,
    this.modelo,
    required this.capturarDiapositivas,
  });

  @override
  int get hashCode =>
      carpetaApuntes.hashCode ^
      carpetaEfectiva.hashCode ^
      modelo.hashCode ^
      capturarDiapositivas.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AjustesDto &&
          runtimeType == other.runtimeType &&
          carpetaApuntes == other.carpetaApuntes &&
          carpetaEfectiva == other.carpetaEfectiva &&
          modelo == other.modelo &&
          capturarDiapositivas == other.capturarDiapositivas;
}

class AvisoDto {
  final PlatformInt64 id;
  final String sessionId;
  final String? topicId;
  final String kind;
  final String texto;
  final String? fecha;
  final PlatformInt64 tsMs;

  const AvisoDto({
    required this.id,
    required this.sessionId,
    this.topicId,
    required this.kind,
    required this.texto,
    this.fecha,
    required this.tsMs,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      sessionId.hashCode ^
      topicId.hashCode ^
      kind.hashCode ^
      texto.hashCode ^
      fecha.hashCode ^
      tsMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AvisoDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          sessionId == other.sessionId &&
          topicId == other.topicId &&
          kind == other.kind &&
          texto == other.texto &&
          fecha == other.fecha &&
          tsMs == other.tsMs;
}

/// Evento en la forma que espera Dart: un enum plano con campos opcionales.
///
/// Se aplana en vez de usar un enum con datos porque el generador produce
/// código mucho más simple de consumir, y la interfaz solo hace un `switch`
/// sobre `tipo`.
class EventoDto {
  /// "niveles" | "frase" | "progreso" | "terminada" | "error"
  final String tipo;
  final double nivelMic;
  final double nivelSistema;
  final PlatformInt64 transcurridoMs;
  final String? track;
  final String? texto;
  final PlatformInt64 inicioMs;
  final PlatformInt64 finMs;
  final bool definitiva;
  final String? fase;
  final double fraccion;
  final String? detalle;
  final double costeUsd;
  final PlatformInt64 avisos;
  final String? mensaje;

  const EventoDto({
    required this.tipo,
    required this.nivelMic,
    required this.nivelSistema,
    required this.transcurridoMs,
    this.track,
    this.texto,
    required this.inicioMs,
    required this.finMs,
    required this.definitiva,
    this.fase,
    required this.fraccion,
    this.detalle,
    required this.costeUsd,
    required this.avisos,
    this.mensaje,
  });

  static Future<EventoDto> default_() =>
      Nucleo.instance.api.cratePuenteEventoDtoDefault();

  @override
  int get hashCode =>
      tipo.hashCode ^
      nivelMic.hashCode ^
      nivelSistema.hashCode ^
      transcurridoMs.hashCode ^
      track.hashCode ^
      texto.hashCode ^
      inicioMs.hashCode ^
      finMs.hashCode ^
      definitiva.hashCode ^
      fase.hashCode ^
      fraccion.hashCode ^
      detalle.hashCode ^
      costeUsd.hashCode ^
      avisos.hashCode ^
      mensaje.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EventoDto &&
          runtimeType == other.runtimeType &&
          tipo == other.tipo &&
          nivelMic == other.nivelMic &&
          nivelSistema == other.nivelSistema &&
          transcurridoMs == other.transcurridoMs &&
          track == other.track &&
          texto == other.texto &&
          inicioMs == other.inicioMs &&
          finMs == other.finMs &&
          definitiva == other.definitiva &&
          fase == other.fase &&
          fraccion == other.fraccion &&
          detalle == other.detalle &&
          costeUsd == other.costeUsd &&
          avisos == other.avisos &&
          mensaje == other.mensaje;
}

class FraseDto {
  final String track;
  final String? speaker;
  final PlatformInt64 inicioMs;
  final PlatformInt64 finMs;
  final String texto;
  final bool definitiva;

  const FraseDto({
    required this.track,
    this.speaker,
    required this.inicioMs,
    required this.finMs,
    required this.texto,
    required this.definitiva,
  });

  @override
  int get hashCode =>
      track.hashCode ^
      speaker.hashCode ^
      inicioMs.hashCode ^
      finMs.hashCode ^
      texto.hashCode ^
      definitiva.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FraseDto &&
          runtimeType == other.runtimeType &&
          track == other.track &&
          speaker == other.speaker &&
          inicioMs == other.inicioMs &&
          finMs == other.finMs &&
          texto == other.texto &&
          definitiva == other.definitiva;
}

class ProcesadaDto {
  final String sessionId;
  final PlatformInt64 frases;
  final PlatformInt64 avisos;
  final double costeUsd;
  final String proveedor;

  const ProcesadaDto({
    required this.sessionId,
    required this.frases,
    required this.avisos,
    required this.costeUsd,
    required this.proveedor,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^
      frases.hashCode ^
      avisos.hashCode ^
      costeUsd.hashCode ^
      proveedor.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProcesadaDto &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          frases == other.frases &&
          avisos == other.avisos &&
          costeUsd == other.costeUsd &&
          proveedor == other.proveedor;
}

class ProveedorDto {
  final String id;
  final String modelo;

  /// De dónde salió la clave, o `None` si no hay.
  final String? origenClave;
  final bool esLocal;

  const ProveedorDto({
    required this.id,
    required this.modelo,
    this.origenClave,
    required this.esLocal,
  });

  @override
  int get hashCode =>
      id.hashCode ^ modelo.hashCode ^ origenClave.hashCode ^ esLocal.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProveedorDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          modelo == other.modelo &&
          origenClave == other.origenClave &&
          esLocal == other.esLocal;
}

class SesionDto {
  final String id;
  final String? topicId;
  final String kind;
  final String status;
  final String? title;
  final PlatformInt64 startedAt;
  final PlatformInt64? endedAt;
  final String? appCaptured;
  final PlatformInt64 numDiapositivas;
  final double costeUsd;

  const SesionDto({
    required this.id,
    this.topicId,
    required this.kind,
    required this.status,
    this.title,
    required this.startedAt,
    this.endedAt,
    this.appCaptured,
    required this.numDiapositivas,
    required this.costeUsd,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      topicId.hashCode ^
      kind.hashCode ^
      status.hashCode ^
      title.hashCode ^
      startedAt.hashCode ^
      endedAt.hashCode ^
      appCaptured.hashCode ^
      numDiapositivas.hashCode ^
      costeUsd.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SesionDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          topicId == other.topicId &&
          kind == other.kind &&
          status == other.status &&
          title == other.title &&
          startedAt == other.startedAt &&
          endedAt == other.endedAt &&
          appCaptured == other.appCaptured &&
          numDiapositivas == other.numDiapositivas &&
          costeUsd == other.costeUsd;
}

class TopicDto {
  final String id;

  /// "course" o "client".
  final String kind;
  final String name;
  final String? person;
  final String? term;
  final bool consentAck;

  const TopicDto({
    required this.id,
    required this.kind,
    required this.name,
    this.person,
    this.term,
    required this.consentAck,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      kind.hashCode ^
      name.hashCode ^
      person.hashCode ^
      term.hashCode ^
      consentAck.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TopicDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          kind == other.kind &&
          name == other.name &&
          person == other.person &&
          term == other.term &&
          consentAck == other.consentAck;
}
